environment:
    global:
        PROJECT_NAME: miri
    matrix:
        - TARGET: x86_64-pc-windows-msvc
        - TARGET: i686-pc-windows-msvc

# branches to build
branches:
  # whitelist
  only:
    - auto
    - try

cache:
    - '%USERPROFILE%\.cargo'
    - '%USERPROFILE%\.rustup'

install:
    # Install Rust
    - curl -sSf -o rustup-init.exe https://win.rustup.rs/
    - rustup-init.exe -y --default-host %TARGET% --default-toolchain beta
    - set PATH=%USERPROFILE%\.cargo\bin;%PATH%
    # Install "master" toolchain
    - cargo install rustup-toolchain-install-master & exit 0
    - set /p RUSTC_HASH=<rust-version
    - rustup-toolchain-install-master -f -n master %RUSTC_HASH% -c rust-src
    - rustup default master
    - rustc --version

build_script:
    - set RUSTFLAGS=-C debug-assertions
    # Build and install miri
    - cargo build --release --all-features --all-targets
    - cargo install --all-features --force --path . --locked --offline
    # Get ourselves a MIR-full libstd, and use it henceforth
    - cargo miri setup
    - set MIRI_SYSROOT=%USERPROFILE%\AppData\Local\rust-lang\miri\cache\HOST

test_script:
    - set RUST_TEST_NOCAPTURE=1
    - set RUST_BACKTRACE=1
    # Test miri
    - cargo test --release --all-features
    # Test cargo integration
    - cd test-cargo-miri
    - '"C:\msys64\mingw64\bin\python3.exe" run-test.py'

after_test:
    # Don't cache "master" toolchain, it's a waste
    - rustup default beta
    - rustup toolchain uninstall master

notifications:
    - provider: Email
      on_build_success: false
