image: ubuntu:latest

tasks:
  - before: echo "..."
    init: |
      cargo install rustup-toolchain-install-master
      ./rustup-toolchain
      ./miri build
    command: echo "Run tests with ./miri test"