language: shell
cache:
  # Cache the global cargo directory, but NOT the local `target` directory which
  # we cannot reuse anyway when the nightly changes (and it grows quite large
  # over time).
  directories:
    - /home/travis/.cargo

os:
- linux
- osx
- windows
dist: xenial

before_script:
# Linux: install extra stuff for cross-compilation
- if [[ "$TRAVIS_OS_NAME" == linux ]]; then sudo apt update && sudo apt install gcc-multilib; fi
# Compute the rust version we use. We do not use "language: rust" to have more control here.
- |
  if [[ "$TRAVIS_EVENT_TYPE" == cron ]]; then
    RUST_TOOLCHAIN=nightly
  else
    RUST_TOOLCHAIN=$(cat rust-version)
  fi
# install Rust
- curl https://build.travis-ci.org/files/rustup-init.sh -sSf | sh -s -- -y --default-toolchain "$RUST_TOOLCHAIN"
- export PATH=$HOME/.cargo/bin:$PATH
- rustc --version

script:
- bash travis.sh

notifications:
  email:
    on_success: never
branches:
  only:
  - master
env:
  global:
  - RUST_TEST_NOCAPTURE=1
  - RUST_BACKTRACE=1
