[package]
name = "miri"
version = "0.1.0"
authors = ["Scott Olson <scott@solson.me>"]
description = "An experimental interpreter for Rust MIR."
repository = "https://github.com/tsion/miri"
license = "ISC"

[[bin]]
name = "miri"
doc = false

[dependencies]
log = "*"
env_logger = "*"
