[workspace]
members = ["proc-macro-crate", "subcrate"]

[package]
name = "cargo-miri-test"
version = "0.1.0"
authors = ["Miri Team"]
edition = "2018"

[dependencies]
byteorder = "1.0"

[dev-dependencies]
rand = { version = "0.7", features = ["small_rng"] }
serde_derive = "1.0" # not actually used, but exercises some unique code path (`--extern` .so file)

[lib]
test = false # test that this is respected (will show in the output)
